### ISSUE TITLE
Check Load-Balance Down (digitalocean)

### ISSUE THREAD

**Issue by namtel-hp** [congthang1/jitsi-kubernetes#1]
I try install, everything running but Load-Balance Down.
How to fix it,

Thanks for support.

**Comment by congthang1** [comment]
Can you post the error here

**Comment by namtel-hp** [comment]
<img width="734" alt="1" src="https://user-images.githubusercontent.com/62697590/98061130-c6346580-1e7d-11eb-9946-77d4b7daf842.png">
<img width="960" alt="2" src="https://user-images.githubusercontent.com/62697590/98061151-d3515480-1e7d-11eb-8866-016f0ca34b9a.png">

**Comment by congthang1** [comment]
Did you update the params << update this >> in all places?

**Comment by namtel-hp** [comment]
Yes, I update all, 
data:
  TZ: Asia/Ho_Chi_Minh
  XMPP_SERVER: meetup.saza.vn # << update this >>  update your main prosody XMPP domain 
  XMPP_BOSH_URL_BASE: http://meetup.saza.vn:5280  # << update this >>
  DOCKER_HOST_ADDRESS: meetup.saza.vn  # << update this >> 
  JICOFO_COMPONENT_SECRET: namtel  # << update this >>  
  JICOFO_AUTH_PASSWORD: namtel # << update this >>  
  JVB_AUTH_PASSWORD: namtel  # << update this >>  


config: |
    # Jitsi Videobridge settings
    # sets the XMPP domain (default: none)
    JVB_HOSTNAME=meetup.saza.vn  
    ## << update this >>

    # sets the hostname of the XMPP server (default: domain if set, localhost otherwise)
    JVB_HOST=

How to:?
      // ## << update this >>
        deploymentInfo: {
            shard: "shard0",
            region: "sfo-2",
            userRegion: "sfo-2"
        },


         - name: OCTO_REGION
              value: tor-1 # << update this >>
      volumes:

**Comment by congthang1** [comment]
Can upload your logs here for web, jicofo and jvb (use kubernetes dashboad on DO).
Also make sure you pointing your domain to the load balancer IP and firewall UDP ports opened

**Comment by namtel-hp** [comment]
Thanks  so much, It worked, How to apply SSL for my domain?

**Comment by congthang1** [comment]
Good to hear that! upload your certificate to the load balancer settings (choose https instead of TCP at port 443).

Or if you know the certificate id, add this to web service:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    service: web
  name: web
  namespace: jitsi
  **annotations:
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: your_certificate_id**
...
```
