### ISSUE TITLE
[Support] How to make Letsencrypt work?

### ISSUE THREAD

**Issue by renepardon** [congthang1/jitsi-kubernetes#11]
Hey,
pretty nice setup so far!

I've added a few env vars to: https://github.com/congthang1/jitsi-kubernetes/blob/main/base/config.yaml

```
DISABLE_HTTPS: "0"
ENABLE_LETSENCRYPT: "1"
LETSENCRYPT_DOMAIN: "my.domain.tld"
LETSENCRYPT_EMAIL: "my@mail.addy"
```

But there is no certificate being generated. Do I miss something?

**Comment by congthang1** [comment]
You need to add ssl at load balancer level.

**Comment by renepardon** [comment]
@congthang1 do you have a hint for me where to start? I usually use cert-manager with ingress to make it work - never did that with load balancer/service itself :)

**Comment by congthang1** [comment]
If on any cloud service you can upload certificate to the load balancer at https 443. This repo is with a cloud load balancer so if on local you need to manage your self a nginx.

**Comment by congthang1** [comment]
Try it on digital ocean as it cheep for both load balancer and bandwidth traffic

**Comment by renepardon** [comment]
Yeah, I run the stack on DO right now. Tried also to issue a certificate manually like described here: https://cert-manager.io/docs/usage/certificate/

so I have a certificate resource available but don't know how to automatically assign it to the load balancer in a way the autorenew also works

**Comment by renepardon** [comment]
Ok, the rest is Digital Ocean related, thanks! :)

**Comment by renepardon** [comment]
Just want to leave a note on how to get it work on DO:

```
doctl compute certificate create --type lets_encrypt --name <NAME> --dns-names <whatever.domain.tld>
```


And then  update the SVC: **service.beta.kubernetes.io/do-loadbalancer-certificate-id:** with the ID being displayed as response
