### ISSUE TITLE
Failed to select initial bridge for participantRegion=null

### ISSUE THREAD

**Issue by renepardon** [congthang1/jitsi-kubernetes#12]
I set up one shard (shard0) on DigitalOcean.
So far so good but I can't start a conference - everyone see their own video only. Jicofo complains about that:

```
Jicofo 2021-07-30 08:30:34.848 WARNING: [110] org.jitsi.jicofo.bridge.BridgeSelectionStrategy.log() Failed to select initial bridge for participantRegion=null
Jicofo 2021-07-30 08:30:34.848 SEVERE: [110] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Can not invite participant -- no bridge available.
```

Whereas Prosody successfully tells me the people who joined already:

```
muc.live.myproject.de:token_moderation                              info	total joined : {"jid":"4d93e691-268c-4ddc-bba4-34c5908be11c@muc.live.myproject.de","room_members":["Tobias Z.","René P."],"type":"joined"}
```

Additional information from JVB logs:

```
Jul 30, 2021 7:13:09 AM org.jitsi.utils.logging2.LoggerImpl log
WARNING: Closed on error:
org.xmlpull.v1.XmlPullParserException: only whitespace content allowed before start tag and not H (position: START_DOCUMENT seen H... @1:1) 
	at org.xmlpull.mxp1.MXParser.parseProlog(MXParser.java:1519)
	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1395)
	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1248)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
	at java.lang.Thread.run(Thread.java:748)

Jul 30, 2021 7:13:09 AM org.jitsi.utils.logging2.LoggerImpl log
WARNING: Cannot set presence extension: not connected.
```

**Comment by congthang1** [comment]
are firewall open for UDP ports on all nodes?

**Comment by renepardon** [comment]
HI @congthang1 
![image](https://user-images.githubusercontent.com/945323/127617375-0ddc57f3-4793-464e-88f0-fb15ae5ef96a.png)

and for Inbound they are also all set - looks like DO does this automatically for me ;)

**Comment by congthang1** [comment]
No they are not default open for all inbound ports, need to modify it. And if you want to automatically add to all new nodes you can use tag instead of instance on the selection of droplets

**Comment by renepardon** [comment]
I did so on all nodes but nothing changed ;(

![image](https://user-images.githubusercontent.com/945323/127622038-5fe626e2-70b7-4e2b-bc5e-4483a8977361.png)

**Comment by congthang1** [comment]
Restart all containers after that. Remember jicofo restart later than web to make sure prosody is on before it start

**Comment by renepardon** [comment]
Looks like I replace a few things which I shouldn't. Works now - thanks for this amazing setup :)
