### ISSUE TITLE
Bad quality and E2E ping error

### ISSUE THREAD

**Issue by spprod35** [congthang1/jitsi-kubernetes#3]
Hello

I failed to activate the websocket with kubernetes and this configuration.
In addition I encounter this error on the client side:

```
BridgeChannel.js:88 WebSocket connection to 'wss://localhost:8443/colibri-ws/10.64.42.83/d95a96ba3855a4ea/108b8e07?pwd=58t8j4rvraal2tibjhd9s64m8o' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
Logger.js:154 2020-11-10T23:44:36.067Z [modules/RTC/BridgeChannel.js] <WebSocket.e.onclose>:  Channel closed by server
react_devtools_backend.js:2450 2020-11-10T23:44:36.067Z [modules/RTC/BridgeChannel.js] <WebSocket.e.onclose>:  Channel closed: 1006 
react_devtools_backend.js:2450 2020-11-10T23:44:40.733Z [modules/RTC/BridgeChannel.js] <l._send>:  Bridge Channel send: no opened channel.
react_devtools_backend.js:2450 2020-11-10T23:44:40.734Z [JitsiConference.js] <u.sendMessage>:  Failed to send E2E ping request or response. undefined
react_devtools_backend.js:2450 2020-11-10T23:44:43.734Z [modules/RTC/BridgeChannel.js] <l._send>:  Bridge Channel send: no opened channel.
react_devtools_backend.js:2450 2020-11-10T23:44:43.735Z [JitsiConference.js] <u.sendMessage>:  Failed to send E2E ping request or response. undefined
react_devtools_backend.js:2450 2020-11-10T23:44:45.735Z [modules/RTC/BridgeChannel.js] <l._send>:  Bridge Channel send: no opened channel.
test:1 Unchecked runtime.lastError: The message port closed before a response was received.
react_devtools_backend.js:2450 2020-11-10T23:44:50.732Z [modules/RTC/BridgeChannel.js] <l._send>:  Bridge Channel send: no opened channel.
```

This has the effect of blocking the quality to a minimum (320x240)

Do you have an idea ?

Thanks

**Comment by spprod35** [comment]
Update after a few hours of testing :

I integrated the following commits from the docker-jitsi-meet repository:
465816b4ebf2babf1b9e6daf007301c1fd17552e
d747bfbe6b72dd86789f61a97372b94c2c19677f
130eb551a7666a9a143343e4ac7e707e3d6c6c02

They have not yet been released in the latest images.
The above commits allow the integration of websocket easily.
I made several configmaps while waiting for a release.

The errors for websockets are no longer there.
However, there remain the E2E errors and the video quality which remains at a minimum

**Comment by congthang1** [comment]
Can try setting on web-configmap.yaml

```
 maxBitratesVideo: {
            low: 200000,
            standard: 500000,
            high: 800000
        },
```

and uncomment this then modify
```
//    minHeightForQualityLvl: {
        //        360: 'standard,
        //        720: 'high'
        //    }
        // },
```

**Comment by spprod35** [comment]
I have tried this, to no avail.
I was able to find a topic saying to deactivate the simulcast.
I did this to no avail a few days ago.

However, I noticed today, that there were 2 occurrences for "disableSimulcast".
I had not changed the correct value ...

Define "config.disableSimulcast = true;" at the end of the "web-configmap.yaml" file so that the HD quality returns while jitsi fixes the bug.
