### ISSUE TITLE
you are the only one in the meeting

### ISSUE THREAD

**Issue by ramazanulucay** [congthang1/jitsi-kubernetes#4]
I have installed to digitalocean. But system doesn't work. It says, "you are the only one in the meeting". How can i fix it. 

![image](https://user-images.githubusercontent.com/9122498/102297238-f7fe1900-3f5f-11eb-96b3-7b136b804cee.png)

My site: https://1e1.ramazanulucay.com

Thank you.

**Comment by congthang1** [comment]
http-bind not connected. I think you didnt open firewall

**Comment by ramazanulucay** [comment]
How can I open firewall?

**Comment by congthang1** [comment]
go here https://cloud.digitalocean.com/networking/firewalls
then create new firewall, apply to tag of your kubernetes start with k8s:
https://cloud.digitalocean.com/networking/firewalls 
![Uploading Screen Shot 2020-12-16 at 15.48.56.png…]()

**Comment by ramazanulucay** [comment]
I changed it but the problem continues. httpd-bind fails 502. Did I make another mistake?
![image](https://user-images.githubusercontent.com/9122498/102328727-7d9dbb00-3f98-11eb-98e8-fcfda89802a7.png)

**Comment by congthang1** [comment]
add to  TCP too

**Comment by ramazanulucay** [comment]
I didn't solve problem and I created new kubernetes. Now when two people are connected, 
CONFERENCE FAILED: conference.videobridgeNotAvailable error and restarts.

**Comment by ramazanulucay** [comment]
There is the following error in the jvb log file.

{"log":"Caused by: java.io.FileNotFoundException: /config/jvb.conf (No such file or directory)\n","stream":"stderr","time":"2020-12-16T14:12:03.652645337Z"}
{"log":"\u0009at java.io.FileInputStream.open0(Native Method)\n","stream":"stderr","time":"2020-12-16T14:12:03.652908148Z"}
{"log":"\u0009at java.io.FileInputStream.open(FileInputStream.java:195)\n","stream":"stderr","time":"2020-12-16T14:12:03.653191087Z"}
{"log":"\u0009at java.io.FileInputStream.\u003cinit\u003e(FileInputStream.java:138)\n","stream":"stderr","time":"2020-12-16T14:12:03.653202738Z"}
{"log":"\u0009at com.typesafe.config.impl.Parseable$ParseableFile.reader(Parseable.java:629)\n","stream":"stderr","time":"2020-12-16T14:12:03.653949379Z"}
{"log":"\u0009at com.typesafe.config.impl.Parseable.reader(Parseable.java:99)\n","stream":"stderr","time":"2020-12-16T14:12:03.653963758Z"}
{"log":"\u0009at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:233)\n","stream":"stderr","time":"2020-12-16T14:12:03.653968096Z"}
{"log":"\u0009at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)\n","stream":"stderr","time":"2020-12-16T14:12:03.653971923Z"}
{"log":"\u0009... 15 more\n","stream":"stderr","time":"2020-12-16T14:12:03.653975614Z"}

**Comment by congthang1** [comment]
did you deploy jvbs?

**Comment by ramazanulucay** [comment]
Yes I deployed with "Deploy the JVBs on kubernetes jvb-shard0"

**Comment by ramazanulucay** [comment]
I checked  5347 port, and It is open.

**Comment by ramazanulucay** [comment]
You can see the error from the http://1e1.ramazanulucay.com/test address.

**Comment by ramazanulucay** [comment]
Will any action be taken with Docker?

**Comment by congthang1** [comment]
how is jicofo logs? did it register any jvb?

**Comment by congthang1** [comment]
Sorry firewall was on wrong place above.
Should set it here
<img width="1211" alt="Screen Shot 2020-12-21 at 10 47 10" src="https://user-images.githubusercontent.com/9101559/102737462-11e19680-437a-11eb-872d-39d3a9075299.png">
